export const imageList = {
  knight_eris: require('./knight-eris.jpg').default,
  knightEris2: require('./knight-eris-2.jpg').default,
  knightEris2Icon: require('./knight-eris-2-icon.jpg').default,
  egao2: require('./egao2.png').default,
  logoErisKirase: require('./logo-eris-kirase.png').default,
  logoErisKirase2: require('./logo-eris-kirase-2.png').default,
  nomalEris: require('./normal-eris.jpg').default,
  nomalErisIcon: require('./normal-eris-icon.jpg').default,
  summerEris: require('./summer-eris.jpg').default,
  summerEris2: require('./summer-eris-2.jpg').default,
  summerEris2Icon: require('./summer-eris-2-icon.jpg').default,
  valentineEris: require('./valentine-eris.jpg').default,
  eriot: require('./eriot.jpg').default,
  receptionistEris: require('./receptionist-eris.jpg').default,
  maidEris: require('./maid-eris.jpg').default,
  picFrame: require('./pic_frame.png').default,
  lastRun: require('./last_run.png').default,
  perperEris: require('./perperEris.png').default,
  anniversaryLogo: require('./2yearsanniversarycelebration.png').default,
  ogpimg: require('./ogpImage.png').default,
}
